// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBcgLI4SUU3QGkq9R9ASTSt6QjpW3enlDQ',
    appId: '1:134085653898:web:61339e3b851a90151b8473',
    messagingSenderId: '134085653898',
    projectId: 'zporter-board-dev',
    authDomain: 'zporter-board-dev.firebaseapp.com',
    storageBucket: 'zporter-board-dev.firebasestorage.app',
    measurementId: 'G-SQTLB8M5PT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBB1l3bCAdbTeY5K994umyWdOhSk_H9rKw',
    appId: '1:134085653898:android:c6778df57e903ba61b8473',
    messagingSenderId: '134085653898',
    projectId: 'zporter-board-dev',
    storageBucket: 'zporter-board-dev.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAgpJWBk_Na0E3xBcas1DBEBRmuvHW4el8',
    appId: '1:134085653898:ios:10b8f4c871d4a2a41b8473',
    messagingSenderId: '134085653898',
    projectId: 'zporter-board-dev',
    storageBucket: 'zporter-board-dev.firebasestorage.app',
    androidClientId: '134085653898-a2787uqbdujnvkhgerb07sd2f5qcij3d.apps.googleusercontent.com',
    iosClientId: '134085653898-i4ok6frvearr4bmj635988of676isjt8.apps.googleusercontent.com',
    iosBundleId: 'com.example.zporterTacticalBoard',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAgpJWBk_Na0E3xBcas1DBEBRmuvHW4el8',
    appId: '1:134085653898:ios:10b8f4c871d4a2a41b8473',
    messagingSenderId: '134085653898',
    projectId: 'zporter-board-dev',
    storageBucket: 'zporter-board-dev.firebasestorage.app',
    androidClientId: '134085653898-a2787uqbdujnvkhgerb07sd2f5qcij3d.apps.googleusercontent.com',
    iosClientId: '134085653898-i4ok6frvearr4bmj635988of676isjt8.apps.googleusercontent.com',
    iosBundleId: 'com.example.zporterTacticalBoard',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBcgLI4SUU3QGkq9R9ASTSt6QjpW3enlDQ',
    appId: '1:134085653898:web:da7ece3f0be315201b8473',
    messagingSenderId: '134085653898',
    projectId: 'zporter-board-dev',
    authDomain: 'zporter-board-dev.firebaseapp.com',
    storageBucket: 'zporter-board-dev.firebasestorage.app',
    measurementId: 'G-HNYGXNYXDP',
  );

}